Create user/notification rule: allow using existing ones
heimweh/go-pagerduty pull request #80
Opened 2022-02-06 11:28 UTC by Padorax

Similar to https://github.com/heimweh/go-pagerduty/commit/fdaf4fec91903e4232d83876cbf54139d8619b21.

If the new user/notification_rule to be added is duplicate, check and fetch the existing one successfully.
This feature is useful in terraform provider, as it can sync existing user/notification_rule automatically to terraform states.

2022-02-08 06:14 UTC, drastawi commented on pagerduty/user.go
> +		if e, ok := err.(*Error); !ok || strings.Compare(fmt.Sprintf("%v", e.Errors), "[User Contact method must be unique]") != 0 {
I asked PD if we can hope to return a 409 here in the future as a more reliable error check, but for now this is probably all we can do.

2022-02-08 06:14 UTC, drastawi approved these changes
Looks great. Thanks @Padorax

2022-02-08 06:16 UTC, drastawi commented on pagerduty/user.go
> +	return nil, nil, fmt.Errorf("[Email has already been taken]")
@Padorax should we just return error here?
```suggestion
	return nil, nil, error)
```

2022-02-09 15:13 UTC, drastawi approved these changes

2022-02-28 22:06 UTC, stmcallister requested changes
@Padorax Thanks for adding this feature! I like the direction you're taking it. However, I'm getting the following error while running the code.

```
pagerduty/user.go:241:19: type error is not an expression
```
Please fix this issue so I can approve the PR. Thanks!!

2022-02-28 22:06 UTC, stmcallister commented on pagerduty/user.go
> +// ListContactMethods lists contact methods for a user.
Please match the function name in the comments with the actual function name

2022-03-01 06:42 UTC, Padorax commented on pagerduty/user.go
> +// ListContactMethods lists contact methods for a user.
Updated, thanks!

2022-03-01 06:43 UTC, Padorax commented
@stmcallister Thanks for the review, all addressed now!

2022-03-10 02:36 UTC, Padorax commented
>

2022-03-15 18:41 UTC, stmcallister approved these changes
Looks good! Thanks for fixing that bug!

2022-03-15 18:41 UTC, merged